#!/bin/bash
# usage:
#   bright;
#   bright u; bright d;
#   bright h; bright mh; bright m; bright ml; bright l;

# ln -s in /usr/local/bin

# crontab -e  entry:
#   0 * * * * /usr/local/bin/bright


# ddcutil (external monitors)
# light (laptop)

newDell="DELL U2719D";
oldDell="DELL U2410";

# Shorthand command to set monitor brightness
ddcSet(){
  ddcutil setvcp 10 $2 --model "$1" 2> /dev/null
}

# set monitor to double its prev value, truncated to int
# 0 25 50 100
upBrightness(){
  model=$1;
  prev=$(ddcutil getvcp 10 --model "$model" 2> /dev/null | grep -Eo '= *[0-9]*,' | grep -Eo '[0-9]*');
  double=$(echo "scale = 0; ($prev * 2) / 1" | bc -l);

  if (( $double > 100 )); then ddcSet "$model" 1OO;
  elif (( $double == 0 )); then ddcSet "$model" 25;
  else ddcSet "$model" $double;
  fi
}

# set monitor to half its prev value, truncated to int
# 100 50 25 0
downBrightness(){
  model=$1;
  prev=$(ddcutil getvcp 10 --model "$model" 2> /dev/null | grep -Eo '= *[0-9]*,' | grep -Eo '[0-9]*');
  half=$(echo "scale = 0; ($prev * 0.5) / 1" | bc -l);

  if (( $half < 25 ));
  then ddcSet "$model" 0;
  else ddcSet "$model" $half;
  fi
}

setDisplay(){
  model=$1;
  brightness=$2;
  prev=$(ddcutil getvcp 10 --model "$model" 2> /dev/null | grep -Eo '= *[0-9]*,' | grep -Eo '[0-9]*');
  if [[ $brightness != $prev ]]; then ddcSet "$model" $brightness; fi
}

setBrightness(){
  case $1 in
    h)  newDellVal=100;;
    mh) newDellVal=77;;
    m)  newDellVal=58;;
    ml) newDellVal=34;;
    l)  newDellVal=18;;
    *) ;;
  esac
  setDisplay "$newDell" $newDellVal &

  case $1 in
    h)  oldDellVal=88;;
    mh) oldDellVal=60;;
    m)  oldDellVal=56;;
    ml) oldDellVal=32;;
    l)  oldDellVal=16;;
  esac
  setDisplay "$oldDell" $oldDellVal &

  case $1 in
    h)  laptopVal=100;;
    mh) laptopVal=80;;
    m)  laptopVal=60;;
    ml) laptopVal=40;;
    l)  laptopVal=21;;
  esac
  # sleep 3s
  light -S $laptopVal &
}


# If the script is called from Cron or CLI without an argument: 'bright'
# Set brightness of monitor and laptop based on current time
if [ -z "${1+x}" ]; then
  H=$(date +%-H)
  if   (( "$H" <= 4 )); then setBrightness "l";
  elif (( "$H" <= 5 )); then setBrightness "ml";
  elif (( "$H" <= 8 )); then setBrightness "m";
  elif (( "$H" <= 9 )); then setBrightness "mh";
  elif (( "$H" <= 10 )); then setBrightness "h";
  elif (( "$H" <= 16 )); then setBrightness "mh";
  elif (( "$H" <= 20 )); then setBrightness "m";
  elif (( "$H" <= 23 )); then setBrightness "ml";
  elif (( "$H" <= 24 )); then setBrightness "l";
  else echo "Error"
  fi
else
  # if the script is called with an argument: 'bright u'
  # Increase, decrease, or set monitor brightness
  if [[ $1 == 'u' ]]; then
    upBrightness "$newDell";
    upBrightness "$oldDell";
  elif [[ $1 == 'd' ]]; then
    downBrightness "$newDell";
    downBrightness "$oldDell";
  else
    # h, mh ,m, ml, l
    setBrightness $1
  fi
fi

