#!/bin/bash
# usage:
#   bright;
#   bright u; bright d;
#   bright h; bright mh; bright m; bright ml; bright l;

# ln -s in /usr/local/bin

# crontab -e  entry:
#   0 * * * * /usr/local/bin/bright


# ddcutil (external monitors)
# light (laptop)


# Shorthand command to set monitor brightness
ddcSet(){
  ddcutil setvcp 10 $2 -d $1 2> /dev/null
}

# set monitor to double its prev value, truncated to int
# 0 25 50 100
upBrightness(){
  displayNum=$1;
  prev=$(ddcutil getvcp 10 -d $displayNum 2> /dev/null | grep -Eo '= *[0-9]*,' | grep -Eo '[0-9]*');
  double=$(echo "scale = 0; ($prev * 2) / 1" | bc -l);

  if (( $double > 100 )); then ddcSet $displayNum 1OO;
  elif (( $double == 0 )); then ddcSet $displayNum 25;
  else ddcSet $displayNum $double;
  fi
}

# set monitor to half its prev value, truncated to int
# 100 50 25 0
downBrightness(){
  displayNum=$1;
  prev=$(ddcutil getvcp 10 -d $displayNum 2> /dev/null | grep -Eo '= *[0-9]*,' | grep -Eo '[0-9]*');
  half=$(echo "scale = 0; ($prev * 0.5) / 1" | bc -l);

  if (( $half < 25 ));
  then ddcSet $displayNum 0;
  else ddcSet $displayNum $half;
  fi
}

setDisplay(){
  displayNum=$1;
  brightness=$2;
  prev=$(ddcutil getvcp 10 -d $displayNum 2> /dev/null | grep -Eo '= *[0-9]*,' | grep -Eo '[0-9]*');
  if [[ $brightness != $prev ]]; then ddcSet $displayNum $brightness; fi
}

setBrightness(){
  case $1 in
    h)  newDell=100;;
    mh) newDell=79;;
    m)  newDell=58;;
    ml) newDell=37;;
    l)  newDell=17;;
    *) ;;
  esac

  setDisplay 2 $newDell &

  case $1 in
    h)  oldDell=88;;
    mh) oldDell=60;;
    m)  oldDell=56;;
    ml) oldDell=28;;
    l)  oldDell=0;;
  esac

  setDisplay 1 $oldDell &

  case $1 in
    h)  laptop=100;;
    mh) laptop=80;;
    m)  laptop=60;;
    ml) laptop=40;;
    l)  laptop=21;;
  esac

  sleep 3s
  light -S $laptop &
}


# If the script is called from Cron or CLI without an argument: 'bright'
# Set brightness of monitor and laptop based on current time
if [ -z "${1+x}" ]; then
  H=$(date +%-H)
  if   (( "$H" <= 6 )); then setBrightness "l";
  elif (( "$H" <= 7 )); then setBrightness "ml";
  elif (( "$H" <= 8 )); then setBrightness "m";
  elif (( "$H" <= 9 )); then setBrightness "mh";
  elif (( "$H" <= 10 )); then setBrightness "h";
  elif (( "$H" <= 15 )); then setBrightness "mh";
  elif (( "$H" <= 17 )); then setBrightness "m";
  elif (( "$H" <= 18 )); then setBrightness "ml";
  elif (( "$H" <= 24 )); then setBrightness "l";
  else echo "Error"
  fi
else
  # if the script is called with an argument: 'bright u'
  # Increase, decrease, or set monitor brightness
  if [[ $1 == 'u' ]]; then
    upBrightness 2;
    upBrightness 1;
  elif [[ $1 == 'd' ]]; then
    downBrightness 2;
    downBrightness 1;
  else
    # h, mh ,m, ml, l
    setBrightness $1
  fi
fi

